### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lumonad** [Oksana-anaskO/First#1]
Вобщем выглядит неплохо но покопавшись в коде есть несколько нюансов
1. Шрифт не подключен
Ты указала фонт фемили но не подключила сам файл шрифта. Есть шрифты которые установлены по умолчанию на большинстве компьютеров/телефонов, но здесь используется кастомный которые надо вручную подключить. 
На сайте гугл фонтсов тебе надо выбрать стилистику(в твоем случае тебе говорят что ты будешь использовать этот шрифт в двух жирностях 400 и 700) И когда ты выберешь должна увидеть справа как на скрине `<link>` который надо вставить в хтмл в хеад часть, ну и сам цсс для фонт фемили. В фонт фемили принято указывать несколько шрифтов в порядке убывания, что бы если твой щрифт не подключится по каким то причинам то использовать наиболее подходящий шрифт из тех что зачастую можно найти на компах.
<img width="1748" alt="Screen Shot 2021-04-10 at 5 52 31 PM" src="https://user-images.githubusercontent.com/4449597/114288523-8faed800-9a25-11eb-8cb4-32e8adbe0f31.png">

2. `body` не надо указывать ширину, боди это твой главный элемент и его размеры должны быть равны размерам физического окна браузера где ты смотришь сайт. Если ты хочешь ограничить контентную часть используй какой то wrapper:

```css
.wrapper {
  width: 1024px;
  // horizontal centering of block elements
  margin: 0 auto;
}
```
3. используй css resets, разные бразуеры имеют разные стили по умолчанию для разных элементов, что бы сайт выглядел одинаково во всех браузерах принято "обнулять" дефолтные стили браузеров https://css-tricks.com/reboot-resets-reasoning/ 
4. `.card-holder` выглядит бесполезным, у него нет стилей. Старайся обходиться меньшим колчеством хтмл элементов а тем более не оставляй бесполезных элементов
5. `.card` он не отцентрован ни по горизонтали ни по вертикали, когда ты выставляешь конкретные марджины в пикселях, он будет отцентрован тольео для конкретной ширины(как в твоем случае для 1440px) что некорректно и кто то откроет на 1366 или 1024 или 720 и у него эта карточка не будет отцентрована
один вариант как просто отцентровать по горихонтали это дать блоку стиль `margin: 0 auto;`, центровать по вертикали таким обрахзом не получиться. Есть другой способ центровать элементы через `flexbox`. Flexbox вообще очень полезная техника что бы управлять расположением элементов, вот тут есть гайд как использовать эти свойства https://css-tricks.com/snippets/css/a-guide-to-flexbox/
6. Блок `.counters` у тебя сделан на флоатах, но сам блок не имеет высоты, что может повлечь нежелательные последствия для блоков после него(у тебя таковых нет) что бы избежать этого для флоатов используется техника `clearfix` https://css-tricks.com/snippets/css/clear-fix/ . Но вообще такой подход уже устарел лучше выравнять блочные элементы в рядок с помощью того же `flexbox`
7. Всю твою карточку ты выставила четкую высоту, сейчас это для тебя сработало хорошо, но всегда держи в голове что любой дизайн не вечен и адаптируется к потребностям клиента/бизнеса и тд и что ты должна пытаться написать наиболее гибкий код которые позволит с легкость расширить элемент по высоте. Например клиент захочет добавить еще какой то контент под `.counters` в текушей имплементации он у тебя просто выпадет за пределы карточки. Попробей убрать высоту у самой карточки и регулируй с паддингами и высотой(натурально а не выставленой черз height) контента

**Comment by lumonad** [comment]
Еще пару моментов:
- `small` тег слегка устаревший попробуй использовать спан с классом
- `span {
    font-weight: 400;
    color: hsl(0, 0%, 59%);
}` слишком глобальный стиль, спан довольно часто используемый элемент и у тебя все спаны на этой страничке получат этот стиль что не совсем правильно
- ты боди задала  `font-weight: 700` я придерживаюсь правила давать в боди стиль тексту наиболее часто встречаемому обычно самый частый текст на странице это не болд(не 700)

**Comment by Oksana-anaskO** [comment]
Спасибо за отзыв)
1)Долго мучалась со шрифтом не знала как его подключить, в итоге скачала на комп и у меня он красивенько появился на сайте)Но теперь я поняла, что это не решение проблемы)

**Comment by Oksana-anaskO** [comment]
А эти линки 2 и вставлять?
